### ISSUE TITLE
'slice' object has no attribute 'encode'

### ISSUE THREAD

**Issue by NickSeigalLCOG** [lanzagar/orange3-hdf5#1]
I am encountering this error when trying to load from an HDF5 file.

`'list' object has no attribute 'encode'`

**Comment by vrindger** [comment]
i'm getting this too...

**Comment by HANhuiyu** [comment]
same..

**Comment by sonnt20** [comment]
same +1

**Comment by lanzagar** [comment]
Although this addon is not maintained (it was a prototype from over 6 years ago) I tried it now with the latest version of Orange and it loaded the included test file (orangecontrib/hdf5/datasets/orange.hdf5).
If someone can reproduce the mentioned error - can you post the complete error traceback and the steps that result in the error.
